version: "3.8"

services:
  redis:
    container_name: redis_freelance
    build: ./redis
    restart: always
    networks:
      - freelance_network

  django:
    build:
      context: ./senderdjango
      dockerfile: Dockerfile
    volumes:
      - ./senderdjango:/usr/src/app
      - ./senderdjango/db.sqlite3:/usr/src/app/db.sqlite3
      - static_volume:/usr/src/app/staticfiles
#      - ./certbot/www:/var/www/certbot/:ro
#      - ./certbot/conf/:/etc/nginx/ssl/:ro

    ports:
      - "8000:80"
#      - "443:443"
    restart: always
    networks:
      - freelance_network
    depends_on:
      - redis
      - bot
    env_file:
      - Bot/.env


#  webserver:
#    image: nginx:latest
#    ports:
#      - 80:80
#      - 443:443
#    restart: always
#    volumes:
#      - ./nginx/conf/:/etc/nginx/conf.d/:ro
#      - ./certbot/www:/var/www/certbot/:ro
#      - ./certbot/conf/:/etc/nginx/ssl/:ro
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw

  bot:
    build:
      context: ./Bot
      dockerfile: Dockerfile
    networks:
      - freelance_network
    depends_on:
      - redis
    restart: always

networks:
  freelance_network:
    driver: bridge

volumes:
  static_volume: