version: "3.8"

services:
  redis:
    container_name: redis_freelance
    build: ./redis
    restart: always
    networks:
      - freelance_network

  django:
    build:
      context: ./senderdjango
      dockerfile: Dockerfile
    volumes:
      - ./senderdjango:/usr/src/app
      - ./senderdjango/db.sqlite3:/usr/src/app/db.sqlite3
      - ./nginx/conf/:/etc/nginx/nginx.conf/:ro
      - ./certbot/www/:/var/www/certbot/:ro
    ports:
      - "80:80"
      - "443:443"
    restart: always
    networks:
      - freelance_network
    depends_on:
      - redis
      - bot
    env_file:
      - Bot/.env

  bot:
    build:
      context: ./Bot
      dockerfile: Dockerfile
    networks:
      - freelance_network
    depends_on:
      - redis
    restart: always

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw


networks:
  freelance_network:
    driver: bridge

volumes:
  static_volume: