version: "3.8"

services:
  redis:
    container_name: redis_freelance
    build: ./redis
    restart: always
    networks:
      - freelance_network

  django:
    build:
      context: ./senderdjango
      dockerfile: Dockerfile
    volumes:
      - ./senderdjango:/usr/src/app
      - ./senderdjango/db.sqlite3:/usr/src/app/db.sqlite3
      - static_volume:/usr/src/app/staticfiles
      - ./certbot/www/:/var/www/certbot/:ro
    ports:
      - "8000:80"
      - "443:443"
    restart: always
    networks:
      - freelance_network
    depends_on:
      - redis
      - bot
    env_file:
      - Bot/.env

  bot:
    build:
      context: ./Bot
      dockerfile: Dockerfile
    networks:
      - freelance_network
    depends_on:
      - redis
    restart: always

  certbot:
    image: certbot/certbot
    volumes:
      - ./letsencrypt:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: '/bin/sh -c "trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;"'


networks:
  freelance_network:
    driver: bridge

volumes:
  static_volume: