# Generated by Django 5.0.3 on 2024-03-06 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledTask',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('day_of_week', models.CharField(max_length=20)),
                ('chat_id', models.IntegerField()),
                ('time', models.TimeField()),
                ('task', models.TextField()),
                ('task_name', models.CharField(max_length=100)),
            ],
        ),
    ]
