# Generated by Django 4.2.11 on 2024-03-07 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledtask',
            name='time',
            field=models.TextField(),
        ),
    ]
